### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fturco** [jirilebl/ra#2]
I noticed your book is licensed under either CC-BY-SA or CC-BY-NC-SA. But what's the point of that? If someone wants to sell your book they will pick CC-BY-SA and ignore the other license. My humble suggestion is to choose one license only, preferably CC-BY-SA (which is a free license, as in freedom). Unless there is some other motivation I don't know, of course...

P.S. Please note I'm not a lawyer.

P.S. According to [this](https://wiki.creativecommons.org/wiki/Wiki/cc_license_compatibility) article, CC-BY-SA and CC-BY-NC-SA are incompatible.

**Comment by jirilebl** [comment]
Well, the point is that if another project is under the NC variant, then without the NC option they wouldn't be able to use this text.  It is precisely the incompatibility issue.  This is not simply theoretical, there was a project under the NC license that used content from the diffy qs book.

By the way, this book was originally under the NC license only.
