### ISSUE TITLE
The LaTeX for Example 0.3.22 doesn’t render correctly.

### ISSUE THREAD

**Issue by gapry** [jirilebl/ra#5]
The render issue is shown in the following screenshot. 

![Example 0.3.22.](https://github.com/jirilebl/ra/assets/4116872/e63f8406-00b4-493e-ad59-ed02423a9978)

My Browser is Firefox 123.0 (64-bit).

**Comment by jirilebl** [comment]
Thanks, just fixed it in commit b4a8228d773533d9745caf95fcf63dd05ba4f941

Actually I just fixed it by hand in the online version by removing those commands which do not work in mathjax, but in the next version it will get built properly (basically we make allowbreak into an empty macro).

Thanks
